doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        dql:
            datetime_functions:
                year: DoctrineExtensions\Query\Mysql\Year
                ceil: DoctrineExtensions\Query\Mysql\Ceil
                floor: DoctrineExtensions\Query\Mysql\Floor
                month: DoctrineExtensions\Query\Mysql\Month
                day: DoctrineExtensions\Query\Mysql\Day
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Core'
                prefix: 'App\Entity\Core'
                alias: AppCore
            App\Core\Term:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Core/Term'
                prefix: 'App\Entity\Core\Term'
                alias: AppCoreTerm
            App\Core\PersonTrait:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Core/PersonTrait'
                prefix: 'App\Entity\Core\PersonTrait'
                alias: AppCorePersonTrait

