framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'formations-geforp@univ-amu.fr'
        headers:
            From: 'Formations Geforp <formations-geforp@univ-amu.fr>'
